#let acronyms = (
  BaaS: "Backend-as-a-Service",
  CoAP: "Constrained Application Protocol",
  CSS: "Cascading Style Sheets",
  GND: "Ground",
  GPIO: "General Purpose Input/Output",
  HTTP: "Hypertext Transfer Protocol",
  I2C: "Inter-Integrated Circuit",
  IoT: "Internet of Things",
  IP: "Internet Protocol",
  IR: "Infrarot",
  JSON: "JavaScript Object Notation",
  LED: "Light Emitting Diode",
  LWT: "Last Will and Testament",
  MAC: "Media Access Control",
  MQTT: "Message Queuing Telemetry Transport",
  OSI: "Open Systems Interconnection",
  PHY: "Physical Layer",
  REST: "Representational State Transfer",
  SPA: "Single Page Application",
  TCP: "Transmission Control Protocol",
  ToF: "Time-of-Flight",
  URI: "Uniform Resource Identifier",
  WLAN: "Wireless Local Area Network",
)
