#let acronyms = (
  API: "Application Programming Interface",
  APSP: "All-Pairs Shortest Path",
  BEV: "Battery Electric Vehicle",
  "CI/CD": "Continuous Integration / Continuous Deployment",
  CMND: "Capacitated Multicommodity Network Design",
  CSV: "Comma-Separated Values",
  DHBW: "Duale Hochschule Baden-Württemberg",
  GHCR: "GitHub Container Registry",
  HSBI: "Hochschule Bielefeld",
  IATA: "International Air Transport Association",
  JSON: "JavaScript Object Notation",
  LKW: "Lastkraftwagen",
  LNS: "Large Neighborhood Search",
  MILP: "Mixed-Integer Linear Program",
  NFP: "Network Flow Planning",
  OR: "Operations Research",
  OSRM: "Open Source Routing Machine",
  SND: "Service Network Design",
  "UN/LOCODE": "United Nations Code for Trade and Transport Locations",
)

